[package]
name = "probe-rs-flash-nostd"
version.workspace = true
edition.workspace = true
description = "no_std flash programming for probe-rs"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version = "1.95"

[dependencies]
probe-rs-adi = { path = "../probe-rs-adi" }
probe-rs-target-nostd = { path = "../probe-rs-target-nostd" }
defmt = { version = "0.3", optional = true }

[features]
default = []
defmt = ["dep:defmt", "probe-rs-adi/defmt", "probe-rs-target-nostd/defmt"]

[lints]
workspace = true
